# Generated by Django 2.2.11 on 2020-04-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceAndCommand',
        ),
        migrations.DeleteModel(
            name='DeviceAndMode',
        ),
        migrations.DeleteModel(
            name='DeviceAndNotification',
        ),
        migrations.DeleteModel(
            name='DeviceAndState',
        ),
        migrations.DeleteModel(
            name='DeviceCommand',
        ),
        migrations.DeleteModel(
            name='DeviceMode',
        ),
        migrations.DeleteModel(
            name='DeviceState',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.DeleteModel(
            name='MailTypeRef',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserAndCommand',
        ),
    ]
