# Generated by Django 2.2.12 on 2020-04-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_devicecommand_devicemode_devicenotification_devicestate_devicetyperef_mailtyperef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicenotification',
            name='noti_type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
