# Generated by Django 2.2.12 on 2020-04-21 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20200421_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/profile_pictures')),
                ('identity_num', models.CharField(max_length=10, unique=True)),
                ('birth', models.DateField()),
                ('gender', models.CharField(choices=[('Эр', 'Эрэгтэй'), ('Эм', 'Эмэгтэй')], default='Эр', max_length=2)),
                ('phone_num', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
