# Generated by Django 2.2.12 on 2020-04-21 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20200421_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicecommand',
            old_name='command_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='devicecommand',
            old_name='command_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='devicemode',
            old_name='mode_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='devicemode',
            old_name='mode_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='devicestate',
            old_name='state_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='devicestate',
            old_name='state_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='devicetyperef',
            old_name='type_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='devicetyperef',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mailtyperef',
            old_name='type_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='mailtyperef',
            old_name='type_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default_profile.png', upload_to='images/profile_pictures'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/default_device.png', upload_to='images/device_pictures')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DeviceTypeRef')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
