# Generated by Django 2.2.12 on 2020-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200421_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='devicecommand',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='devicemode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='devicenotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='devicestate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='devicetyperef',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mailtyperef',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='command',
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='төхөөрөмж', max_length=100),
        ),
    ]
