# Generated by Django 2.2.12 on 2020-04-21 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200421_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userandcommand',
            options={},
        ),
        migrations.RemoveField(
            model_name='userandcommand',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='userandcommand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
