# Generated by Django 2.2.12 on 2020-04-21 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200421_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceandcommand',
            options={'ordering': ['-device', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userandcommand',
            options={'ordering': ['-user', '-created_at']},
        ),
        migrations.RenameField(
            model_name='devicenotification',
            old_name='noti_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='devicenotification',
            old_name='noti_type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='userandcommand',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.RenameModel(
            old_name='MailTypeRef',
            new_name='EMailTypeRef',
        ),
        migrations.CreateModel(
            name='DeviceAndState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Device')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.DeviceState')),
            ],
            options={
                'ordering': ['-device', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAndNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Device')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.DeviceNotification')),
            ],
            options={
                'ordering': ['-device', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAndMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Device')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.DeviceMode')),
            ],
            options={
                'ordering': ['-device', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAndEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('msg_body', models.CharField(max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/email_pictures')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Device')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.EMailTypeRef')),
            ],
            options={
                'ordering': ['-device', '-created_at'],
            },
        ),
    ]
