# Generated by Django 2.2.12 on 2020-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200422_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceandemail',
            name='msg_body',
            field=models.TextField(),
        ),
    ]
