# Generated by Django 2.2.12 on 2020-04-25 11:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200425_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=phone_field.models.PhoneField(max_length=11),
        ),
    ]
