# Generated by Django 2.2.12 on 2020-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200426_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='images/profile_pictures'),
        ),
    ]
