# Generated by Django 2.2.12 on 2020-05-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20200426_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
