# Generated by Django 2.2.12 on 2020-05-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200523_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isActive',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
